### ISSUE TITLE
Library is not compiling in Xcode 13

### ISSUE THREAD

**Issue by francofantillo** [espressif/esp-idf-provisioning-ios#38]
The ESP provision library will not compile on Xcode 13. See the following screenshot.
![Error](https://user-images.githubusercontent.com/29694577/134989273-5bd6181e-2fff-47f8-8f7b-1b48b2ef4b22.png)

**Comment by vikas-chandra-mnnit** [comment]
Hi @francofantillo We are in the process of updating our library and apps to support iOS 15 and Xcode 13. We will update you in this thread, once we push out a new library update.

**Comment by m-shahbaz-naeem** [comment]
Having the same issue...!!!
Thanks...!!!
<img width="942" alt="Screen Shot 2021-10-06 at 12 11 34 AM" src="https://user-images.githubusercontent.com/71810324/136087709-280907f1-3eb3-47f5-a18e-8121730ffa90.png">

**Comment by vikas-chandra-mnnit** [comment]
@francofantillo @ChaossAdept7 @m-shahbaz-naeem We have fixed the compilation issue and pushed an update to the library. Please update your ESPProvision SDK to version 2.0.14. Thanks.

**Comment by TomMettam** [comment]
Now it no longer builds on earlier versions of XCode - please update your minimum requirements to reflect this

**Comment by vikas-chandra-mnnit** [comment]
@TomMettam , thanks for the feedback. Starting from now we will mention the supported Xcode version in our release note. If you are working with older Xcode I suggest switching to the previous version of ESPProvision SDK using podfile.

**Comment by TomMettam** [comment]
Mainly I meant on https://github.com/espressif/esp-idf-provisioning-ios#requirements which still shows XCode 11 under minimum requirements
